### ISSUE TITLE
Installation error on Mac OS X

### ISSUE THREAD

**Issue by DaZzz** [mapzen/mapbox-vector-tile#40]
I've got the following error:
```bash 
$ pip install mapbox-vector-tile

Collecting mapbox-vector-tile
  Using cached mapbox-vector-tile-0.2.1.tar.gz
Requirement already up-to-date: setuptools in ./lib/python3.5/site-packages (from mapbox-vector-tile)
Requirement already up-to-date: protobuf in ./lib/python3.5/site-packages (from mapbox-vector-tile)
Collecting shapely (from mapbox-vector-tile)
  Using cached Shapely-1.5.13.tar.gz
    Complete output from command python setup.py egg_info:
    Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
    Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zv/cq564h150vg1m4jn7zyr3sv00000gp/T/pip-build-07112n1y/shapely/setup.py", line 38, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/private/var/folders/zv/cq564h150vg1m4jn7zyr3sv00000gp/T/pip-build-07112n1y/shapely/shapely/_buildcfg.py", line 185, in <module>
        lgeos = load_dll('geos_c', fallbacks=alt_paths)
      File "/private/var/folders/zv/cq564h150vg1m4jn7zyr3sv00000gp/T/pip-build-07112n1y/shapely/shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib']

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zv/cq564h150vg1m4jn7zyr3sv00000gp/T/pip-build-07112n1y/shapely/
```

So I had to install `geos` library manually (`brew install geos`) to fix this problem. Consider adding this step to installation section.

**Comment by zerebubuth** [comment]
Hi @DaZzz, gald to hear you got it working. I've added a paragraph about Shapely and its dependency on GEOS in #41. Would that have helped make the installation steps clearer?

**Comment by DaZzz** [comment]
@zerebubuth now it's great. :+1:

**Comment by zerebubuth** [comment]
Awesome, thanks!
